#!/bin/sh

mkdir -p -m 750 ${SNAP_DATA}/php

mysqld_pid_file_path=$SNAP_DATA/mysql/`hostname`.pid
# Wait for mysql to be up and running, since we need to make sure
# we run the upgrade process.
echo "Waiting for mysql..."
while [ ! -f "$mysqld_pid_file_path" ]; do
	sleep 1
done

# Wait until we have a mysql password
echo "Obtaining mysql credentials..."
password_path=$SNAP_DATA/mysql/"$SNAP_NAME"_password
timeout=10
while [ $timeout -gt 0 -a ! -e $password_path ]; do
	timeout=$((timeout-1))
	sleep 1
done
if [ ! -e $password_path ]; then
	echo -n "Timed out while attempting to obtain mysql password. "
	echo -n "This isn't unusual when starting up for the first time after "
	echo "an install or an upgrade. Will try again."
	exit 1
fi

# Tends to be between 30-50MB
average_php_memory_requirement=50
total_memory=$(mawk '/MemTotal/ {printf "%d", $2/1024}' /proc/meminfo)
export PHP_FPM_MAX_CHILDREN=$(($total_memory/$average_php_memory_requirement))
export INSTALL_PREFIX=$SNAP
export INSTALL_PREFIX_DATA=$SNAP_DATA/asterisk/
export ASTERISK_CMD="asterisk -C $INSTALL_PREFIX_DATA/etc/asterisk/asterisk.conf"
export MYSQLSOCK="$SNAP_DATA/mysql/mysql.sock"

php-fpm -R -F --fpm-config ${SNAP}/config/php/php-fpm.conf -c ${SNAP}/config/php
